///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace T2GO
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the T2GORepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
    [RepositoryFolder("77c3bf80-9f42-4af0-9cd9-c982d8253562")]
    public partial class T2GORepository : RepoGenBaseFolder
    {
        static T2GORepository instance = new T2GORepository();

        /// <summary>
        /// Gets the singleton class instance representing the T2GORepository element repository.
        /// </summary>
        [RepositoryFolder("77c3bf80-9f42-4af0-9cd9-c982d8253562")]
        public static T2GORepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public T2GORepository() 
            : base("T2GORepository", "/", null, 0, false, "77c3bf80-9f42-4af0-9cd9-c982d8253562", ".\\RepositoryImages\\T2GORepository77c3bf80.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("77c3bf80-9f42-4af0-9cd9-c982d8253562")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
    public partial class T2GORepositoryFolders
    {
    }
#pragma warning restore 0436
}