///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace rx_github_proj
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the rx_github_projRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
    [RepositoryFolder("b160ab99-1415-4bbe-96db-4a42afdb9e4f")]
    public partial class rx_github_projRepository : RepoGenBaseFolder
    {
        static rx_github_projRepository instance = new rx_github_projRepository();

        /// <summary>
        /// Gets the singleton class instance representing the rx_github_projRepository element repository.
        /// </summary>
        [RepositoryFolder("b160ab99-1415-4bbe-96db-4a42afdb9e4f")]
        public static rx_github_projRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public rx_github_projRepository() 
            : base("rx_github_projRepository", "/", null, 0, false, "b160ab99-1415-4bbe-96db-4a42afdb9e4f", ".\\RepositoryImages\\rx_github_projRepositoryb160ab99.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("b160ab99-1415-4bbe-96db-4a42afdb9e4f")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
    public partial class rx_github_projRepositoryFolders
    {
    }
#pragma warning restore 0436
}