///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace DFDSGroup
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("7bf45a58-721b-473e-acec-3f791511f10f", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the DFDSGroupRepository repository.
        /// </summary>
        public static DFDSGroupRepository repo = DFDSGroupRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://uat.dfds-unified.com/en-gb/group/about-dfds' with browser 'chrome' in normal mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("https://uat.dfds-unified.com/en-gb/group/about-dfds", "chrome", "", false, false, false, false, false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DFDSGoogleChrome' at 3046;67.", repo.DFDSGoogleChrome.SelfInfo, new RecordItemIndex(1));
            repo.DFDSGoogleChrome.Self.Click("3046;67");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=870,Height=165}) on item 'AboutUsDFDSGroup.SomeDivTag.AboutDFDS'.", repo.AboutUsDFDSGroup.SomeDivTag.AboutDFDSInfo, new RecordItemIndex(2));
            Validate.ContainsImage(repo.AboutUsDFDSGroup.SomeDivTag.AboutDFDSInfo, AboutDFDS_Screenshot1, AboutDFDS_Screenshot1_Options);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AboutUsDFDSGroup.PassengerFerries' at 126;31.", repo.AboutUsDFDSGroup.PassengerFerriesInfo, new RecordItemIndex(3));
            repo.AboutUsDFDSGroup.PassengerFerries.Click("126;31");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -1080 units.", new RecordItemIndex(4));
            Mouse.ScrollWheel(-1080);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AboutUsDFDSGroup.SomeDivTag.OurHistory' at 88;21.", repo.AboutUsDFDSGroup.SomeDivTag.OurHistoryInfo, new RecordItemIndex(5));
            repo.AboutUsDFDSGroup.SomeDivTag.OurHistory.Click("88;21");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AboutUsDFDSGroup.SomeDivTag.H1Tag404PageNotFound' at 80;47.", repo.AboutUsDFDSGroup.SomeDivTag.H1Tag404PageNotFoundInfo, new RecordItemIndex(6));
            repo.AboutUsDFDSGroup.SomeDivTag.H1Tag404PageNotFound.Click("80;47");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
        CompressedImage AboutDFDS_Screenshot1
        { get { return repo.AboutUsDFDSGroup.SomeDivTag.AboutDFDSInfo.GetScreenshot1(new Rectangle(0, 0, 870, 165)); } }

        Imaging.FindOptions AboutDFDS_Screenshot1_Options
        { get { return Imaging.FindOptions.Default; } }

#endregion
    }
#pragma warning restore 0436
}
