///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace DFDSGroup
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("7bf45a58-721b-473e-acec-3f791511f10f", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the DFDSGroupRepository repository.
        /// </summary>
        public static DFDSGroupRepository repo = DFDSGroupRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://prod.dfds-unified.com/en-gb/' with browser 'chrome' in normal mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("https://prod.dfds-unified.com/en-gb/", "chrome", "", false, false, false, false, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'DFDSFerriesLogisticsFreightEurop.Grid.WhereverWeGoWeStartWithYou'.", repo.DFDSFerriesLogisticsFreightEurop.Grid.WhereverWeGoWeStartWithYouInfo, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.DFDSFerriesLogisticsFreightEurop.Grid.WhereverWeGoWeStartWithYouInfo, "Visible", "True");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DFDSFerriesLogisticsFreightEurop.SomeDivTag.FreightShipping' at 132;32.", repo.DFDSFerriesLogisticsFreightEurop.SomeDivTag.FreightShippingInfo, new RecordItemIndex(2));
            repo.DFDSFerriesLogisticsFreightEurop.SomeDivTag.FreightShipping.Click("132;32");
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'DFDSFerriesLogisticsFreightEurop.Grid.PortToPortFreightShippingSolutions'.", repo.DFDSFerriesLogisticsFreightEurop.Grid.PortToPortFreightShippingSolutionsInfo, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.DFDSFerriesLogisticsFreightEurop.Grid.PortToPortFreightShippingSolutionsInfo, "Visible", "True");
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'DFDSFerriesLogisticsFreightEurop.Grid.HeadlineBlockFilterTextContainer'.", repo.DFDSFerriesLogisticsFreightEurop.Grid.HeadlineBlockFilterTextContainerInfo, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.DFDSFerriesLogisticsFreightEurop.Grid.HeadlineBlockFilterTextContainerInfo, "Visible", "True");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DFDSFerriesLogisticsFreightEurop.SomeDivTag.LogisticsSolutions' at 299;108.", repo.DFDSFerriesLogisticsFreightEurop.SomeDivTag.LogisticsSolutionsInfo, new RecordItemIndex(5));
            repo.DFDSFerriesLogisticsFreightEurop.SomeDivTag.LogisticsSolutions.Click("299;108");
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'DFDSFerriesLogisticsFreightEurop.Grid.LogisticsAndSupplyChainSolutions'.", repo.DFDSFerriesLogisticsFreightEurop.Grid.LogisticsAndSupplyChainSolutionsInfo, new RecordItemIndex(6));
            Validate.AttributeEqual(repo.DFDSFerriesLogisticsFreightEurop.Grid.LogisticsAndSupplyChainSolutionsInfo, "Visible", "True");
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'DFDSFerriesLogisticsFreightEurop.Grid.HeadlineBlockFilterTextContainer'.", repo.DFDSFerriesLogisticsFreightEurop.Grid.HeadlineBlockFilterTextContainerInfo, new RecordItemIndex(7));
            Validate.AttributeEqual(repo.DFDSFerriesLogisticsFreightEurop.Grid.HeadlineBlockFilterTextContainerInfo, "Visible", "True");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DFDSFerriesLogisticsFreightEurop.SomeDivTag.AboutDFDS' at 65;47.", repo.DFDSFerriesLogisticsFreightEurop.SomeDivTag.AboutDFDSInfo, new RecordItemIndex(8));
            repo.DFDSFerriesLogisticsFreightEurop.SomeDivTag.AboutDFDS.Click("65;47");
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'DFDSFerriesLogisticsFreightEurop.Grid.TheDFDSGroup'.", repo.DFDSFerriesLogisticsFreightEurop.Grid.TheDFDSGroupInfo, new RecordItemIndex(9));
            Validate.AttributeEqual(repo.DFDSFerriesLogisticsFreightEurop.Grid.TheDFDSGroupInfo, "Visible", "True");
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
