///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace BBGO
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("38fe1f71-9b65-45b6-9280-4f377e0e54e1", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the BBGORepository repository.
        /// </summary>
        public static BBGORepository repo = BBGORepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'http://nordea.se' with browser 'chrome' in normal mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("http://nordea.se", "chrome", "", false, false, false, false, false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -480 units.", new RecordItemIndex(1));
            Mouse.ScrollWheel(-480);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Start.TilePKingComCandyCrushSodaSagaKgqvn' at 26;36.", repo.Start.TilePKingComCandyCrushSodaSagaKgqvnInfo, new RecordItemIndex(2));
            repo.Start.TilePKingComCandyCrushSodaSagaKgqvn.Click("26;36");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BankenFoerHelaDinEkonomiNordeaSe.Element1351658240' at 3157;69.", repo.BankenFoerHelaDinEkonomiNordeaSe.Element1351658240Info, new RecordItemIndex(3));
            repo.BankenFoerHelaDinEkonomiNordeaSe.Element1351658240.Click("3157;69");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BankenFoerHelaDinEkonomiNordeaSe.Element1351658240' at 3056;61.", repo.BankenFoerHelaDinEkonomiNordeaSe.Element1351658240Info, new RecordItemIndex(4));
            repo.BankenFoerHelaDinEkonomiNordeaSe.Element1351658240.Click("3056;61");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BankenFoerHelaDinEkonomiNordeaSe.Element1351658240' at 2780;494.", repo.BankenFoerHelaDinEkonomiNordeaSe.Element1351658240Info, new RecordItemIndex(5));
            repo.BankenFoerHelaDinEkonomiNordeaSe.Element1351658240.Click("2780;494");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BankenFoerHelaDinEkonomiNordeaSe' at 3200;49.", repo.BankenFoerHelaDinEkonomiNordeaSe.SelfInfo, new RecordItemIndex(6));
            repo.BankenFoerHelaDinEkonomiNordeaSe.Self.Click("3200;49");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
