///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace rx_git_proj
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("9c8e9f8c-5a3c-4469-be9d-49f4b525a9a4", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the rx_git_projRepository repository.
        /// </summary>
        public static rx_git_projRepository repo = rx_git_projRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'http://nordea.se' with browser 'chrome' in normal mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("http://nordea.se", "chrome", "", false, false, false, false, false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BankenFoerHelaDinEkonomiNordeaSe.Element788958864' at 2294;68.", repo.BankenFoerHelaDinEkonomiNordeaSe.Element788958864Info, new RecordItemIndex(1));
            repo.BankenFoerHelaDinEkonomiNordeaSe.Element788958864.Click("2294;68");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BankenFoerHelaDinEkonomiNordeaSe.Element788958864' at 1888;200.", repo.BankenFoerHelaDinEkonomiNordeaSe.Element788958864Info, new RecordItemIndex(2));
            repo.BankenFoerHelaDinEkonomiNordeaSe.Element788958864.Click("1888;200");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BankenFoerHelaDinEkonomiNordeaSe.Element788958864' at 1545;456.", repo.BankenFoerHelaDinEkonomiNordeaSe.Element788958864Info, new RecordItemIndex(3));
            repo.BankenFoerHelaDinEkonomiNordeaSe.Element788958864.Click("1545;456");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BankenFoerHelaDinEkonomiNordeaSe.Element788958864' at 991;1080.", repo.BankenFoerHelaDinEkonomiNordeaSe.Element788958864Info, new RecordItemIndex(4));
            repo.BankenFoerHelaDinEkonomiNordeaSe.Element788958864.Click("991;1080");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
