///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace rx_git_proj
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the rx_git_projRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
    [RepositoryFolder("c92d7753-c722-4491-9fdb-956000881286")]
    public partial class rx_git_projRepository : RepoGenBaseFolder
    {
        static rx_git_projRepository instance = new rx_git_projRepository();
        rx_git_projRepositoryFolders.DocumentsAppFolder _documents;
        rx_git_projRepositoryFolders.ExplorerAppFolder _explorer;
        rx_git_projRepositoryFolders.Explorer1AppFolder _explorer1;
        rx_git_projRepositoryFolders.BankenFoerHelaDinEkonomiNordeaSeAppFolder _bankenfoerheladinekonominordease;
        rx_git_projRepositoryFolders.KeyPromptFormAppFolder _keypromptform;

        /// <summary>
        /// Gets the singleton class instance representing the rx_git_projRepository element repository.
        /// </summary>
        [RepositoryFolder("c92d7753-c722-4491-9fdb-956000881286")]
        public static rx_git_projRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public rx_git_projRepository() 
            : base("rx_git_projRepository", "/", null, 0, false, "c92d7753-c722-4491-9fdb-956000881286", ".\\RepositoryImages\\rx_git_projRepositoryc92d7753.rximgres")
        {
            _documents = new rx_git_projRepositoryFolders.DocumentsAppFolder(this);
            _explorer = new rx_git_projRepositoryFolders.ExplorerAppFolder(this);
            _explorer1 = new rx_git_projRepositoryFolders.Explorer1AppFolder(this);
            _bankenfoerheladinekonominordease = new rx_git_projRepositoryFolders.BankenFoerHelaDinEkonomiNordeaSeAppFolder(this);
            _keypromptform = new rx_git_projRepositoryFolders.KeyPromptFormAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("c92d7753-c722-4491-9fdb-956000881286")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Documents folder.
        /// </summary>
        [RepositoryFolder("6a65fc1c-b837-4fcb-997b-40be9a947794")]
        public virtual rx_git_projRepositoryFolders.DocumentsAppFolder Documents
        {
            get { return _documents; }
        }

        /// <summary>
        /// The Explorer folder.
        /// </summary>
        [RepositoryFolder("fafd4c48-4d54-4594-808f-b3967a6e93e9")]
        public virtual rx_git_projRepositoryFolders.ExplorerAppFolder Explorer
        {
            get { return _explorer; }
        }

        /// <summary>
        /// The Explorer1 folder.
        /// </summary>
        [RepositoryFolder("c09f05e1-4b0c-4947-90f5-39f1bcbffc50")]
        public virtual rx_git_projRepositoryFolders.Explorer1AppFolder Explorer1
        {
            get { return _explorer1; }
        }

        /// <summary>
        /// The BankenFoerHelaDinEkonomiNordeaSe folder.
        /// </summary>
        [RepositoryFolder("6575f584-721e-4cc4-bf67-dab981655387")]
        public virtual rx_git_projRepositoryFolders.BankenFoerHelaDinEkonomiNordeaSeAppFolder BankenFoerHelaDinEkonomiNordeaSe
        {
            get { return _bankenfoerheladinekonominordease; }
        }

        /// <summary>
        /// The KeyPromptForm folder.
        /// </summary>
        [RepositoryFolder("719a841c-d237-4740-a4bd-d1f14b1530fd")]
        public virtual rx_git_projRepositoryFolders.KeyPromptFormAppFolder KeyPromptForm
        {
            get { return _keypromptform; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
    public partial class rx_git_projRepositoryFolders
    {
        /// <summary>
        /// The DocumentsAppFolder folder.
        /// </summary>
        [RepositoryFolder("6a65fc1c-b837-4fcb-997b-40be9a947794")]
        public partial class DocumentsAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _clipboardInfo;
            RepoItemInfo _titlebarInfo;

            /// <summary>
            /// Creates a new Documents  folder.
            /// </summary>
            public DocumentsAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Documents", "/form[@title='Documents']", parentFolder, 30000, null, true, "6a65fc1c-b837-4fcb-997b-40be9a947794", "")
            {
                _clipboardInfo = new RepoItemInfo(this, "Clipboard", "element[3]//container[@accessiblename='Lower Ribbon']/container[@accessiblename='']/container[@accessiblename='Home']/toolbar[@accessiblename='Clipboard']", 30000, null, "17570665-f58d-4a79-9eb8-60f9d3a5f025");
                _titlebarInfo = new RepoItemInfo(this, "TitleBar", "titlebar[@automationid='TitleBar']", 30000, null, "59fbe5cd-a340-44ae-abd6-b2dbf4833806");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6a65fc1c-b837-4fcb-997b-40be9a947794")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6a65fc1c-b837-4fcb-997b-40be9a947794")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Clipboard item.
            /// </summary>
            [RepositoryItem("17570665-f58d-4a79-9eb8-60f9d3a5f025")]
            public virtual Ranorex.ToolBar Clipboard
            {
                get
                {
                    return _clipboardInfo.CreateAdapter<Ranorex.ToolBar>(true);
                }
            }

            /// <summary>
            /// The Clipboard item info.
            /// </summary>
            [RepositoryItemInfo("17570665-f58d-4a79-9eb8-60f9d3a5f025")]
            public virtual RepoItemInfo ClipboardInfo
            {
                get
                {
                    return _clipboardInfo;
                }
            }

            /// <summary>
            /// The TitleBar item.
            /// </summary>
            [RepositoryItem("59fbe5cd-a340-44ae-abd6-b2dbf4833806")]
            public virtual Ranorex.TitleBar TitleBar
            {
                get
                {
                    return _titlebarInfo.CreateAdapter<Ranorex.TitleBar>(true);
                }
            }

            /// <summary>
            /// The TitleBar item info.
            /// </summary>
            [RepositoryItemInfo("59fbe5cd-a340-44ae-abd6-b2dbf4833806")]
            public virtual RepoItemInfo TitleBarInfo
            {
                get
                {
                    return _titlebarInfo;
                }
            }
        }

        /// <summary>
        /// The ExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("fafd4c48-4d54-4594-808f-b3967a6e93e9")]
        public partial class ExplorerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _tortoisegitclient1runningwindowInfo;
            RepoItemInfo _ranorexstudio1runningwindowInfo;

            /// <summary>
            /// Creates a new Explorer  folder.
            /// </summary>
            public ExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer", "/menubar[@class='Shell_TrayWnd']", parentFolder, 30000, null, true, "fafd4c48-4d54-4594-808f-b3967a6e93e9", "")
            {
                _tortoisegitclient1runningwindowInfo = new RepoItemInfo(this, "TortoiseGitClient1RunningWindow", "container[@controlid='40965']//toolbar[@accessiblename='Running applications']/button[@accessiblename~'^TortoiseGit\\ client\\ -\\ 1\\ ru']", 30000, null, "a078d16a-9302-406d-9174-0e82017be454");
                _ranorexstudio1runningwindowInfo = new RepoItemInfo(this, "RanorexStudio1RunningWindow", "container[@controlid='40965']//toolbar[@accessiblename='Running applications']/button[@accessiblename~'^RanorexStudio\\ -\\ 1\\ running']", 30000, null, "9940a059-f4bd-4e36-8164-8a872258be8e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("fafd4c48-4d54-4594-808f-b3967a6e93e9")]
            public virtual Ranorex.MenuBar Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MenuBar>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("fafd4c48-4d54-4594-808f-b3967a6e93e9")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TortoiseGitClient1RunningWindow item.
            /// </summary>
            [RepositoryItem("a078d16a-9302-406d-9174-0e82017be454")]
            public virtual Ranorex.Button TortoiseGitClient1RunningWindow
            {
                get
                {
                    return _tortoisegitclient1runningwindowInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The TortoiseGitClient1RunningWindow item info.
            /// </summary>
            [RepositoryItemInfo("a078d16a-9302-406d-9174-0e82017be454")]
            public virtual RepoItemInfo TortoiseGitClient1RunningWindowInfo
            {
                get
                {
                    return _tortoisegitclient1runningwindowInfo;
                }
            }

            /// <summary>
            /// The RanorexStudio1RunningWindow item.
            /// </summary>
            [RepositoryItem("9940a059-f4bd-4e36-8164-8a872258be8e")]
            public virtual Ranorex.Button RanorexStudio1RunningWindow
            {
                get
                {
                    return _ranorexstudio1runningwindowInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The RanorexStudio1RunningWindow item info.
            /// </summary>
            [RepositoryItemInfo("9940a059-f4bd-4e36-8164-8a872258be8e")]
            public virtual RepoItemInfo RanorexStudio1RunningWindowInfo
            {
                get
                {
                    return _ranorexstudio1runningwindowInfo;
                }
            }
        }

        /// <summary>
        /// The Explorer1AppFolder folder.
        /// </summary>
        [RepositoryFolder("c09f05e1-4b0c-4947-90f5-39f1bcbffc50")]
        public partial class Explorer1AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _list1Info;

            /// <summary>
            /// Creates a new Explorer1  folder.
            /// </summary>
            public Explorer1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer1", "/form[@processname='explorer' and @class='WorkerW' and @instance='0']", parentFolder, 30000, null, true, "c09f05e1-4b0c-4947-90f5-39f1bcbffc50", "")
            {
                _list1Info = new RepoItemInfo(this, "List1", "?/?/list[@controlid='1']", 30000, null, "3beeed60-359c-4280-96c3-fb8224eef852");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c09f05e1-4b0c-4947-90f5-39f1bcbffc50")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c09f05e1-4b0c-4947-90f5-39f1bcbffc50")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The List1 item.
            /// </summary>
            [RepositoryItem("3beeed60-359c-4280-96c3-fb8224eef852")]
            public virtual Ranorex.List List1
            {
                get
                {
                    return _list1Info.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The List1 item info.
            /// </summary>
            [RepositoryItemInfo("3beeed60-359c-4280-96c3-fb8224eef852")]
            public virtual RepoItemInfo List1Info
            {
                get
                {
                    return _list1Info;
                }
            }
        }

        /// <summary>
        /// The BankenFoerHelaDinEkonomiNordeaSeAppFolder folder.
        /// </summary>
        [RepositoryFolder("6575f584-721e-4cc4-bf67-dab981655387")]
        public partial class BankenFoerHelaDinEkonomiNordeaSeAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _element788958864Info;
            RepoItemInfo _element791159776Info;

            /// <summary>
            /// Creates a new BankenFoerHelaDinEkonomiNordeaSe  folder.
            /// </summary>
            public BankenFoerHelaDinEkonomiNordeaSeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("BankenFoerHelaDinEkonomiNordeaSe", "/form[@title~'^Banken\\ för\\ hela\\ din\\ ekono']", parentFolder, 30000, null, true, "6575f584-721e-4cc4-bf67-dab981655387", "")
            {
                _element788958864Info = new RepoItemInfo(this, "Element788958864", "element[@controlid='-788958864']", 30000, null, "c2fd34b6-0f47-4a70-8f99-979b80c6c18e");
                _element791159776Info = new RepoItemInfo(this, "Element791159776", "element[@controlid='-791159776']", 30000, null, "d8cf084d-8923-4e8a-b24a-03c2bf20cd24");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6575f584-721e-4cc4-bf67-dab981655387")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6575f584-721e-4cc4-bf67-dab981655387")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Element788958864 item.
            /// </summary>
            [RepositoryItem("c2fd34b6-0f47-4a70-8f99-979b80c6c18e")]
            public virtual Ranorex.Unknown Element788958864
            {
                get
                {
                    return _element788958864Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Element788958864 item info.
            /// </summary>
            [RepositoryItemInfo("c2fd34b6-0f47-4a70-8f99-979b80c6c18e")]
            public virtual RepoItemInfo Element788958864Info
            {
                get
                {
                    return _element788958864Info;
                }
            }

            /// <summary>
            /// The Element791159776 item.
            /// </summary>
            [RepositoryItem("d8cf084d-8923-4e8a-b24a-03c2bf20cd24")]
            public virtual Ranorex.Unknown Element791159776
            {
                get
                {
                    return _element791159776Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Element791159776 item info.
            /// </summary>
            [RepositoryItemInfo("d8cf084d-8923-4e8a-b24a-03c2bf20cd24")]
            public virtual RepoItemInfo Element791159776Info
            {
                get
                {
                    return _element791159776Info;
                }
            }
        }

        /// <summary>
        /// The KeyPromptFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("719a841c-d237-4740-a4bd-d1f14b1530fd")]
        public partial class KeyPromptFormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _mbtnokInfo;

            /// <summary>
            /// Creates a new KeyPromptForm  folder.
            /// </summary>
            public KeyPromptFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("KeyPromptForm", "/form[@controlname='KeyPromptForm']", parentFolder, 30000, null, true, "719a841c-d237-4740-a4bd-d1f14b1530fd", "")
            {
                _mbtnokInfo = new RepoItemInfo(this, "MBtnOK", "button[@controlname='m_btnOK']", 30000, null, "faac7b5b-1fbf-4a7f-a18d-0f58f755da39");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("719a841c-d237-4740-a4bd-d1f14b1530fd")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("719a841c-d237-4740-a4bd-d1f14b1530fd")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MBtnOK item.
            /// </summary>
            [RepositoryItem("faac7b5b-1fbf-4a7f-a18d-0f58f755da39")]
            public virtual Ranorex.Button MBtnOK
            {
                get
                {
                    return _mbtnokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The MBtnOK item info.
            /// </summary>
            [RepositoryItemInfo("faac7b5b-1fbf-4a7f-a18d-0f58f755da39")]
            public virtual RepoItemInfo MBtnOKInfo
            {
                get
                {
                    return _mbtnokInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}